version: 2.1

commands:
  print_pipeline_id:
    steps:
      - run: echo ${CIRCLE_WORKFLOW_ID}

jobs:
  create_infrastructure:
    docker:
      - image: amazon/aws-cli
    steps:
      - chheckout
      - run:
          name: Ensure backend infra exists
          command: |
            aws cloudformation deploy \
              --template-file template.yml \
              --stack-name backendStack

workflows:
  my_workflow:
    jobs:
      - create_infrastructure