# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
# Use a package of configuration called an orb.
orbs:
  # Declare a dependency on the welcome-orb
  welcome: circleci/welcome-orb@0.4.1
# Orchestrate or schedule a set of jobs

jobs:
  print-hello: 
    docker:
      - image: circleci/node:13.8.0
    steps:
      # - checkout
      - run:
          name: Run Hello
          command: echo "hello"
  
  print-world: 
    docker:
      - image: circleci/node:13.8.0
    steps:
      # - checkout
      - run:
          name: Run World
          command: echo "world"

  print-name:
    docker:
      - image: circleci/node:13.8.0
    steps:
        - run:
            name: Print Name
            command: echo $username

workflows:
  # Name the workflow "welcome"
  welcome:
    # Run the welcome/run job in its own container
    jobs:
      - welcome/run
      - print-hello:
          requires: [welcome/run]
      - print-world:
          requires: [print-hello]
      - print-name
          
