version: 2.1

jobs:
  configure_infrastructure:
    docker:
      - image: python:3.7-alpine3.11
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints: ["3c:16:b8:88:26:e1:40:6f:50:53:1d:ef:30:c4:eb:a3"]
      - run:
          name: Install Dependencies
          command: |
            apk add --update ansible
      - run:
          name: Configure server
          command: |
            ansible-playbook main-remote.yml -i inventory
      # - run:
      #     name: Ensure backend infra exists
      #     command: |
      #       aws cloudformation deploy \
      #         --template-file template.yml \
      #         --stack-name backendStack

workflows:
  my_workflow:
    jobs:
      - configure_infrastructure